In [1]:
#from list
import numpy as np
l = list(range(1,4))
data = np.array(l)
print(data)
print(data[0])
print(data[1])

[1 2 3]
1
2


In [2]:
#tao ndarray tu list
import numpy as np
listID = [1,2,3]
data = np.array(listID)

print(data)
print(data.shape)

[1 2 3]
(3,)


In [3]:
#tao ndarray tu list
import numpy as np
list2D = [[1,2],[3,4],[4,6]]
data = np.array(list2D)

print(data)
print(data.shape)


[[1 2]
 [3 4]
 [4 6]]
(3, 2)


In [5]:
#tao ndarray tu list
import numpy as np
data1 = np.array([1,2,3])
print(data1.dtype)

data2 = np.array([1.,2.,3.])
print(data2.dtype)

data3 = np.array([1,2,3],dtype=np.int64)
print(data3.dtype)


int64
float64
int64


In [4]:
#tao ndarray tu list
import numpy as np
list3D = [[[1,6],[2,2],[3,4]],
          [[4,7],[5,2],[6,9]],
          [[7,7],[8,2],[9,5]]]
data = np.array(list3D)

print(data)
print(data.shape)

[[[1 6]
  [2 2]
  [3 4]]

 [[4 7]
  [5 2]
  [6 9]]

 [[7 7]
  [8 2]
  [9 5]]]
(3, 3, 2)


In [6]:
#update an element
import numpy as np
l = list(range(1,4))
data = np.array(l)
print(data)
data[0]=8
print(data)

[1 2 3]
[8 2 3]


In [7]:
#create numpy array
import numpy as np
arr = np.zeros((2,3))
print(arr)


[[0. 0. 0.]
 [0. 0. 0.]]


In [8]:
#arager() funtion
import numpy as np
arr = np.arange(5)
print(arr)
arr2 = np.arange(0,5,2)
print(arr2)

[0 1 2 3 4]
[0 2 4]


In [9]:
#eye() funtion
import numpy as np
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
#random() funtion
import numpy as np
arr = np.random.random((2,3))
print(arr)

[[0.12017593 0.83660007 0.98389383]
 [0.03720482 0.12510638 0.79023945]]


In [12]:
#where() funtion
import numpy as np
arr = np.arange(5)
print(arr)
condition = arr < 3
out = np.where(condition,arr,arr*2)
print(condition)
print(out)

[0 1 2 3 4]
[ True  True  True False False]
[0 1 2 6 8]


In [14]:
#flatten() funtion
import numpy as np
arr = np.array([[1,2],[3,4]])
out = arr.flatten()
print(arr)
print(out)

[[1 2]
 [3 4]]
[1 2 3 4]
